### ISSUE TITLE
Allow unofficial versions to be used, aka a developer mode

### ISSUE THREAD

**Issue by amirkdv** [ndaniel/fusioncatcher#102]
I understand that the master branch of github repo is not considered official release. But it would be nice to be able to use it anyway because:

* some breaking changes by third parties make the official release unusable for some period of time. For example, atm due to a URL change for human genome annotations (#98) the official release crashes on bootstrap.
* as other issues are introduced and fixed (e.g. my work on #100), even if they are on other people's forks they might need to use them for their own purposes and fusioncatcher shouldn't _crash_ because it's not the official release.

The current issues for having a developer mode where the user can force `bootstrap.py` or `fusioncatcher-build.py` to use a local copy of the repo (not just a downloaded zip file) are these:

* `bootstrap.py` insists on downloading the official release. We can give it a local zip file (i.e. using `--local-fusioncatcher`) but that's a confusing pain to zip up a local copy of the repo and feed it to bootstrap every time one is debugging something which then installs fusion catcher in a different place (so 3 copies!).
* There are multiple version checks sprinkled around that crash (e.g. currently the repo says `fusioncatcher-build` is version 1.10 but the built data from sourceforge is 1.00). In dev mode this should be a warning and not a crash.
* `bootstrap.py` rewrites the shebang of fusioncatcher scripts. In dev mode this should not happen because it's a nightmare when a script overwrites itself.
* when in dev mode one may not want to run full heavy analyses but rather to check that installation works and tests pass. The hardcoded 24 GB minimum memory requirement makes it hard because rarely one has a dev machine with that much memory.

**Comment by amirkdv** [comment]
I have introduced a pull request that addresses all these with minimal change. I have tested `bootstrap`, `fusioncatcher-build` and `fusioncatcher` itself, everything works correctly and tests pass. What it does:

* introduced an environment variable `FUSIONCATCHER_DEV_MODE` which when defined (value does not matter) applies minimal changes to the behavior of `bootstrap.py` and `fusioncatcher-build.py` to make it work using the local copy (i.e. the repo containing the executed script). These different behaviors are:
  * change the variable `FUSIONCATCHER_VERSION` in `bootstrap` to match the one in the local repo and not the official version.
  * do not download the official release in `boostrap.py`. Use the repo containing the invoked script.
  * do not rewrite python shebangs of the working repo.
  * do not crash because build data (large files on sourceforge) and `fusioncatcher-build` have a version mismatch (inevitable).
* match the fusioncatcher version in `/etc/configuration.cfg`. This is not needed when one calls `bootstrap.py` because it overwrites the file but if the user is not calling bootstrap the version mismatch crashes.
* fix a minor inconsistency with STAR versions so that using local copy does not crash
* add a `--min-memory` option to `fusioncatcher` so that in local dev tests one can specify a smaller number than 23000 MB (default, so current behavior is preserved).
* use a 2GB minimum memory in `test/tests.sh` since the inputs are small.

**Comment by amirkdv** [comment]
usage:
```
$ FUSIONCATCHER_DEV_MODE=  bin/bootstrap.py -t -y     # install required tools
$ FUSIONCATCHER_DEV_MODE=  bin/bootstrap.py -t -b -y  # build data
$ FUSIONCATCHER_DEV_MODE=  test/test.sh                # run tests
```

or just set the environment variable in the shell session:
```
$ FUSIONCATCHER_DEV_MODE=  # value does not matter
$ bin/bootstrap.py -t -y
```

**Comment by ndaniel** [comment]
> when in dev mode one may not want to run full heavy analyses but rather to check that installation works and tests pass. The hardcoded 24 GB minimum memory requirement makes it hard because rarely one has a dev machine with that much memory.

That hard coded limit saved a lot of time from debugging potential fake bugs due to little RAM memory limit. BLAT, STAR, and SEQTK need at least that much when working with human genome. For example, SEQTK just crashes when it does not have enough memory (see: https://github.com/lh3/seqtk/issues/46 ). FusionCatcher uses SeqTK a lot and it is almost impossible to predict the memory consumption of SeqTK and thru trial an error I found that 24GB works most of time well enough.
The hardcoded limit can be easily changed as you suggested.

> use a 2GB minimum memory in test/tests.sh since the inputs are small.

I am not sure that is possible because the human genome (that is 13GB when indexed by Bowtie) even if the input would be only one read.

**Comment by ndaniel** [comment]
I have not had yet time to look carefully to this but at first glance it looks like FusionCatcher is supporting this. In the manual is called semi-automatic installation as shown here https://github.com/ndaniel/fusioncatcher/blob/master/doc/manual.md#43---semi-automatic-installation

Shortly, these are the steps:
- get a copy of `boostrap.py` from GitHub => `wget https://github.com/ndaniel/fusioncatcher/blob/master/bin/bootstrap.py`
- run `boostrap.py --dependecies` and download those dependencies into current directory (download the FusionCatcher from GitHub instead of SourceForge and compressed it using zip) => for FusionCatcher from Github do this `git clone https://github.com/ndaniel/fusioncatcher ; zip -9 -r fusioncatcher_v1.10.zip fusioncatcher/`
- run `bootstrap.py --local .` in order to force `bootstrap.py` to use the tools and FusionCatcher which were just downloaded to the local directory instead (taking them from internet).

I haven't check to install FusionCatcher like this in a while but I guess that it should work and at first glance it should provide the most of the features requested here in the developed mode.

**Comment by ndaniel** [comment]
Now I see that you were aware of the `boostrap.py --local`. I need some time to look deeper into this.

**Comment by ndaniel** [comment]
I was wondering if this does what you mean by developer mode, where the GitHub version can be used and installed very easily:
```
mkdir developer-mode
cd developer-mode
wget http://sf.net/projects/fusioncatcher/files/bootstrap.py -O bootstrap.py && python bootstrap.py -t -y
mv fusioncatcher fusioncatcher_official
git clone https://github.com/ndaniel/fusioncatcher/
mv -f fusioncatcher_official/tools/* fusioncatcher/tools/
# trying to merge two configuration files
grep -B 1000 versions fusioncatcher_official/etc/configuration.cfg | head -n -1 > fusioncatcher/etc/c1.cfg
grep -A 1000 versions fusioncatcher/etc/configuration.cfg > fusioncatcher/etc/c2.cfg
cat fusioncatcher/etc/c1.cfg fusioncatcher/etc/c2.cfg > fusioncatcher/etc/configuration.cfg
#
rm -rf fusioncatcher_official
cd fusioncatcher/data
../bin/fusioncatcher-build.py -o human
ln -s human current
```
and now everything should be in `developer-mode/fusioncatcher`.
