### ISSUE TITLE
Fusioncatcher on HCC conda channel

### ISSUE THREAD

**Issue by matq007** [ndaniel/fusioncatcher#108]
Guys from HCC group were kind enough to wrap the application into `conda`. 
https://github.com/unlhcc/hcc-conda-recipes/tree/master/recipes/fusioncatcher/1.00

**Comment by ndaniel** [comment]
Thanks for the great work done here to get FusionCatcher into conda.

I have not tested the FusionCatcher from Conda but looking here https://github.com/unlhcc/hcc-conda-recipes/tree/master/recipes/fusioncatcher/1.00 I would guess that FusionCatcher would not work properly due to SeqTK. FusionCatcher is using a forked SeqTK (that is https://github.com/ndaniel/seqtk ) and not the official SeqTK (that is https://github.com/lh3/seqtk) and these two are incompatible (and the official SeqTK has never accepted the additions done to the SeqTK in the forked SeqTK as shown here https://github.com/lh3/seqtk/pull/91 ). For more info regarding forked SeqTK and Conda see here: https://github.com/ndaniel/fusioncatcher/issues/20 .

The challenge which I see here is how to get a forked tool (that is https://github.com/ndaniel/seqtk ) in the conda?

This has been posted also here: https://github.com/unlhcc/hcc-conda-recipes/issues/2

**Comment by ndaniel** [comment]
Everything looks fine now!

**Comment by matq007** [comment]
Will you update the manual then so people know they can install the tool with conda?

**Comment by ndaniel** [comment]
Yes, I will do that.
Please, could you provide a small example how to install FusionCatcher with conda so I can put it in the manual and also on the official page?
Thanks.
Daniel

**Comment by matq007** [comment]
Sure thing!
You just have to run: `conda install -c hcc fusioncatcher`
The package is available here: https://anaconda.org/HCC/fusioncatcher
Recipe here: https://github.com/unlhcc/hcc-conda-recipes/tree/master/recipes/fusioncatcher/1.00

**Comment by ndaniel** [comment]
Ok. I gave it a test. I installed conda (latest miniconda3). Whe running `conda install -c hcc fusioncatcher`
I got this error:
```
use@linux:~$ conda install -c hcc fusioncatcher
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - fusioncatcher
  - bbmap
  - fusioncatcher
  - blat[version='>=35,<36.0a0']
  - fusioncatcher
  - bowtie[version='>=1.2.0,<1.2.1.0a0']
  - fusioncatcher
  - bowtie2[version='>=2.3.0,<2.3.1.0a0']
  - fusioncatcher
  - bwa[version='>=0.7.12,<0.7.13.0a0']
  - fusioncatcher
  - coreutils[version='>=8.29,<8.30.0a0']
  - fusioncatcher
  - java-jdk
  - fusioncatcher
  - oases
  - fusioncatcher
  - parallel[version='>=20171222,<20171223.0a0']
  - fusioncatcher
  - picard[version='>=2.10.6,<2.10.7.0a0']
  - fusioncatcher
  - samtools[version='>=0.1.19,<0.1.20.0a0']
  - fusioncatcher
  - setuptools[version='>=36.3.0,<36.3.1.0a0']
  - fusioncatcher
  - sra-tools=2.6.2
  - fusioncatcher
  - star=2.5.2b
  - fusioncatcher
  - ucsc-fatotwobit
  - fusioncatcher
  - ucsc-liftover
  - fusioncatcher
  - velvet[version='>=1.2.10,<1.2.11.0a0']

Current channels:

  - https://conda.anaconda.org/hcc/linux-64
  - https://conda.anaconda.org/hcc/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch
```

**Comment by matq007** [comment]
Ah ok, that might be due to missing channels. I am using these channels in my setup:
* anaconda
* bioconda
* conda-forge
* hcc
https://github.com/nf-core/rnafusion/blob/master/tools/fusioncatcher/environment.yml

**Comment by ndaniel** [comment]
The it should be something like this:
```
conda config --add channels bioconda
conda config --add channels conda-forge
conda install -c hcc fusioncatcher
```
Right?

**Comment by matq007** [comment]
Yes, exactly 👍

**Comment by ndaniel** [comment]
I did some small changes by removing some tools which are not really needed by FusionCatcher, that are coreutils and setuptools.

https://github.com/ndaniel/hcc-conda-recipes/commit/e13e17d0985be50002d84b977b8004a92c2650d1
https://github.com/ndaniel/hcc-conda-recipes/commit/b8c486e88ba2f5bc5258d2f9387502a40b27a819

**Comment by ndaniel** [comment]
This bug looks related to conda
https://github.com/ndaniel/fusioncatcher/issues/110
