### ISSUE TITLE
NameError running 0.99.4d beta

### ISSUE THREAD

**Issue by jjellis** [ndaniel/fusioncatcher#11]
Hi,

Whilst running `fusioncatcher` (0.99.4d beta) I got the following error:

```
Traceback (most recent call last):
  File "/fusioncatcher/bin/fusioncatcher.py", line 3584, in <module>
    if len_reads > 40 and options.trim_wiggle:
NameError: name 'len_reads' is not defined
```

On line 3235, I find the following:

```
if os.path.exists(outdir('log_lengths_reads.txt')):
    len_reads = int(file(outdir('log_lengths_reads.txt'),'r').readline().rstrip('\r\n'))
    # reads shorter than this will be skipped from analysis, 34?
    minimum_length_short_read = len_reads
```

Obviously, `log_lengths_reads.txt` does not exist and `len_reads` is not being
set, but what is the real error? Is it an error for the file not to exist (in
which case this should be caught and reported earlier), or is there a sensible
default for `len_reads`? Either way, there is clearly a code path to the use of
`len_reads` when the condition isn't met.

**Comment by ndaniel** [comment]
Hi jjelis!

You are correct. There are some code paths which are not fully covered for some rare situations, like for example when:

- FusionCatcher fails at some step and then it re-started, or
-  **all** the input reads have been filtered out due to being low quality.

Has FusionCatcher been restarted when this error has appeared in your case? If yes, then a workaround would be to manually remove all the temporary files and directories which FusionCatcher has created and start running FusionCatcher again from scratch.

I think that I have fixed exactly the issue which you reported here in the newest release of FusionCatcher, that is v0.99.4e, and which was released today!

Please, report back if it has not been fixed.

**Comment by jjellis** [comment]
Yes, I had restarted a failed run when I got this error message. Deleting files and starting from scratch appears to have worked the second time. The error that cause the first failure was

```
Traceback (most recent call last):
  File "fusioncatcher.py", line 4576, in <module>
    temp_path = temp_flag)
  File "fusioncatcher.py", line 201, in info
    for line in file(fromfile,'r').readlines():
IOError: [Errno 2] No such file or directory: 'log_bowtie_reads_filtered_all-possible-mappings-transcriptome_multiple_map.stdout.txt'
```

I haven't had an opportunity to investigate this first failure (and now that `fusioncatcher` has successfully run, I probably won't). Thanks for your suggestions.
