### ISSUE TITLE
stick with specific Ensembl release 

### ISSUE THREAD

**Issue by ndaniel** [ndaniel/fusioncatcher#116]
A nice feature would be to update the toolset but stick with a specific Ensembl version for smoother long-term data integration with other processed data.

**Comment by af8** [comment]
Hello

I was interested in this feature too, I see that the issue is closed but by reading` fusioncatcher-build.py` help I am not sure if this is possible to specify the Ensembl version ?

Actually, I ran recently into issue #177 so I updated the code from 1.20 to 1.30 but now fusioncatcher refuses to run cause the database (v98) was not built with v1.30.

Thanks

**Comment by af8** [comment]
Just discovered `--ftp-ensembl-path` :-)

**Comment by ndaniel** [comment]
That might or might not work.

The challenge with that is that the supporting several Ensembl releases simultaneously increases exponentially the support effort. FusionCatcher uses other 20+ databases (eg. RefSeq, GeneCode, UCSC, etc.) beside Ensembl and each of those databases have their own version/release. Integrating so many databases and different versions/releases cannot be done automatically (because it is guaranteed that some of those database change their data schema and that breaks the parsers that FusionCatcher is using which need to be fixed manually).

**Comment by af8** [comment]
Sure. I'll give it a try for Ensembl v98 with fusioncatcher-1.30 then 🤞
