### ISSUE TITLE
Exon IDs missing when fusion not at exon boundary

### ISSUE THREAD

**Issue by amirkdv** [ndaniel/fusioncatcher#126]
## Description

My colleagues and I have noticed that the columns indicating the exons implicated in a fusion, i.e. `Exon_1_id(5end_fusion_partner)` and `Exon_2_id(3end_fusion_partner)`, are only populated if the fusion breakpoint in the resulting mRNA transcript is exactly at exon boundary of respective 5' and 3' genes. Specifically, if the fusion breakpoint is in the middle of either 5' or 3' exons this column is missing in FusionCatcher output.

We all found this behavior confusing and only got our clue from the following lines in the manual (emphasis mine):

> Exon_1_id(5end_fusion_partner) Ensembl exon id of the 5' end fusion **exon-exon junction**
Exon_2_id(3end_fusion_partner) Ensembl exon id of the 3' end fusion **exon-exon junction**

and we assume that by "exon-exon junction" the manual meant to refer to the conditions under which the "exon-exon" tag in the description column is present, namely:
> the fusion junction point is exactly at the known exon's borders of both genes forming the candidate fusion

We then proceeded to confirm this behavior on a real dataset as well as a tiny synthetic one including a single fusion both of which confirmed our understanding.

## Questions

* Is our understanding correct? Can you confirm that: exon columns are populated _if and only if_ the fusion breakpoint is exactly at exon boundary? Specifically, that this behavior is independent of any other aspect of fusion (e.g. in-frame/out-of-frame)
* Is this behavior intended? If so:
   * Does it reflect some underlying biology that we are missing or is a limitation of FusionCatcher implementation?
   * It is probably worthwhile explaining this in more detail in the manual. I can volunteer to send a Pull Request for that.
* Is there a graceful way to recover the exon columns? depending on context:
   * (for cases where we run FC on RNA-seq data) a patch that we can maintain ourselves,
   * (for cases where by run downstream analysis on already existing FC output) re-running an internal FC script on existing FC output with different arguments that would populate those columns.

**Comment by ndaniel** [comment]
* Is our understanding correct? Can you confirm that: exon columns are populated _if and only if_ the fusion breakpoint is exactly at exon boundary? Specifically, that this behavior is independent of any other aspect of fusion (e.g. in-frame/out-of-frame)

*Yes, it is correct.*

* Is this behavior intended? If so:
   * Does it reflect some underlying biology that we are missing or is a limitation of FusionCatcher implementation?

*This has nothing to do with biology. In the very beginning FC was able to find fusion genes only when the fusion breakpoint was at the exon boundary (and the exon id was populated). Later new feature was added to FC to find other types of fusion breakpoints but the exon id was not populated anymore (because it is challenging to pinpoint which exon is linked to the fusion)*

   * It is probably worthwhile explaining this in more detail in the manual. I can volunteer to send a Pull Request for that.

*Ok.*

* Is there a graceful way to recover the exon columns? depending on context:
   * (for cases where we run FC on RNA-seq data) a patch that we can maintain ourselves,
   * (for cases where by run downstream analysis on already existing FC output) re-running an internal FC script on existing FC output with different arguments that would populate those columns.

*Is this related to https://github.com/ndaniel/fusioncatcher/issues/127 ?*

**Comment by amirkdv** [comment]
Thank you @ndaniel for the clarifications!

It is only related to #127 to the extent that a similar workaround could have been enough for our purposes but it seems like such a workaround is not possible with existing scripts in FC.

Otherwise we use the exons independently of `Predicted_fused_transcript`. We use them to recognize rows in FC output that correspond to different exon pairs _in the same gene pair_, e.g. `exon 10 (5') * exon 9 (3')` vs `exon 11(5') * exon 9(3')`. In this sense this is more related to #120 (we too sometines get many rows in FC output corresponding to the same 5'-3' gene pair, and we need to somehow group them together for our downstream).

I suppose in cases where exon ids are missing a workaround (for post-FC processing) would be to look up the exon ID from Ensembl using the genomic coordinates provided by FC. I think this should be trivial if one has access to Ensembl (specifically the [exon table](https://useast.ensembl.org/info/docs/api/core/core_schema.html#exon) in an SQL database. Is there a reason why this wouldn't work?

**Comment by ndaniel** [comment]
> I suppose in cases where exon ids are missing a workaround (for post-FC processing) would be to look up the exon ID from Ensembl using the genomic coordinates provided by FC. I think this should be trivial if one has access to Ensembl (specifically the exon table) in an SQL database.

True.

>  Is there a reason why this wouldn't work?

There is no reason. It should work.
