### ISSUE TITLE
source of banned list 

### ISSUE THREAD

**Issue by Sames-Jtudd** [ndaniel/fusioncatcher#136]
Hi there, hope you may be able to help.

I was wondering what the origin of the banned list (https://github.com/ndaniel/fusioncatcher/blob/master/bin/generate_banned.py) is that is provided with the package?

Is this a complitation of all the other lists that suggest a variant is not a genuine somatic fusion eg HPA, GTEx etc. 

Or are there other banned lists that are not provided with the software that are used to complie this list.

Many thanks 
Jamie

**Comment by ndaniel** [comment]
Hi @Sames-Jtudd 

The banned list is a manual compilation of fusion genes that have been found in healhty samples using FusionCatcher, which come from:
- HPA
- BodMap2
- some in-house databases (which are not publicly available).


GTEx is not in banned list because I didn't run FusionCatcher on it. But the fusions found in GTEx get their own label, that is gtex. FusionCatcher gets the GTEx fusions automatically (and not manually) using this: https://github.com/ndaniel/fusioncatcher/blob/master/bin/get_gtex.py

I guess that banned list is not the best name because fusion genes can exit legitimately in healthy cells and healthy people and it is one way of the evolution creates new genes. It is just that when looking to cancer or other diseases probably those are not the fusion type one is looking for.

Usually, I am looking of a combination of labels (eg. banned and GTEx) and therefore it is challenging to say which individually banned lists should be banned or not. Anyway, one can look to Table 2 here:
https://github.com/ndaniel/fusioncatcher/blob/master/doc/manual.md#62---output-data-output-data and see a list of possible banned lists that are used by the FusionCatcher to let user know that those fusions show up also in healthy cells.

**Comment by Sames-Jtudd** [comment]
Hi Daniel, 

thanks for getting back to me so quickly I appreacite your help.
