### ISSUE TITLE
Reads supporting fusion seem to only map to the 3' gene

### ISSUE THREAD

**Issue by tb08** [ndaniel/fusioncatcher#137]
Hello,
Thank you very much for fusioncatcher which is a great and very complete tool.
I have been running it on some human cell line RNAseq we produced and I am trying to assess the validity of one of the candidate fusion pair that fusioncatcher outputs. 
This is what fusion catcher reports:

Gene_1_symbol(5end_fusion_partner) | Gene_2_symbol(3end_fusion_partner) | Fusion_description | Counts_of_common_mapping_reads | Spanning_pairs | Spanning_unique_reads | Longest_anchor_found | Fusion_finding_method | Fusion_point_for_gene_1(5end_fusion_partner) | Fusion_point_for_gene_2(3end_fusion_partner)
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
PAX5 | TNFSF10 | cancer,tumor,reciprocal | 0 | 4 | 5 | 39 | BOWTIE+STAR | 9:36977626:- | 3:172505821:-

I have run fusioncatcher with the option `--visualization-sam` and I tried looking at what reads supported the fusion, however the mapping of the reads does not seem to match their support for the junction or as split pairs: most reads do map to chr3 but none of them maps to the neighbourhood of the first gene on chr9:36977626.
This is an extract from the supporting reads STAR SAM file, focusing only on chr3 and chr9 mappings:

QNAME | FLAG | RNAME | POS | MAPQ | CIGAR
-- | -- | -- | -- | -- | --
0R2zF_supports_fusion_pair/2 | 16 | 3 | 172506035 | 255 | 101M
0Vj5H_supports_fusion_junction/2 | 0 | 3 | 172505596 | 40 | 1S97M3S
0R2zL_supports_fusion_pair/2 | 16 | 3 | 172506077 | 255 | 101M
0UvUE_supports_fusion_junction/2 | 0 | 3 | 172505778 | 18 | 101M
14mf4_supports_fusion_junction/1 | 0 | 3 | 172505737 | 21 | 100M1S
0UvUE_supports_fusion_junction/1 | 16 | 3 | 172505968 | 38 | 101M
0UvUE_supports_fusion_junction/1 | 272 | 9 | 113667688 | 38 | 13S42M46S
0UvUE_supports_fusion_junction/1 | 272 | 3 | 51557439 | 38 | 13S43M45S
0Vj5H_supports_fusion_junction/1 | 16 | 3 | 172505754 | 18 | 101M
15jGN_supports_fusion_junction/2 | 16 | 3 | 172505764 | 17 | 101M
15jGN_supports_fusion_junction/2 | 272 | 3 | 184607624 | 17 | 4S97M
0ab0a_supports_fusion_junction/1 | 0 | 3 | 115064525 | 11 | 14S87M
0ab0a_supports_fusion_junction/1 | 272 | 3 | 61948183 | 11 | 87M14S
0ab0a_supports_fusion_junction/1 | 256 | 3 | 64518855 | 11 | 18S83M
0ab0a_supports_fusion_junction/1 | 272 | 9 | 126840239 | 11 | 1S60M1I34M5S
0R2zC_supports_fusion_pair/2 | 16 | 3 | 172505847 | 25 | 101M
15jGN_supports_fusion_junction/1 | 0 | 3 | 172505736 | 21 | 101M
14mf4_supports_fusion_junction/2 | 16 | 3 | 172505758 | 18 | 101M
14mf4_supports_fusion_junction/2 | 272 | 9 | 135530037 | 18 | 5S5M1D91M
14mf4_supports_fusion_junction/2 | 272 | 3 | 101745304 | 18 | 12S80M9S
0R2zC_supports_fusion_pair/1 | 272 | 3 | 61948155 | 11 | 1S94M6S
0R2zJ_supports_fusion_pair/2 | 256 | 3 | 140179482 | 11 | 30S66M5S

Am I missing something?

**Comment by ndaniel** [comment]
Hello @tb08 

so FusionCatcher (FC) has many independent parts. The main part, which is the main goal of FC, is to find the fusions. The one of the secondary parts is the visualization of fusions. There are cases where FC is able to find the fusion (by using the power of 4 or 5 aligners simultaneously) but the visualization part might not be able to visualize the found fusion because is the visualization part is using different methods (it is using only 1/2 aligners independently) and it is not that developed.

In general I found that the best for visualizing fusion is the BLAT tool from UCSC genome browser: https://genome.ucsc.edu/cgi-bin/hgBlat?command=start . Just copy and paste the reads there and that should do it. 

This is a workaround until the `--visualization-sam ` will be improved more.

**Comment by tb08** [comment]
Hi @ndaniel thanks a lot for your detailed answer. 
I actually also tried running BLAT on each of the supporting reads and I found the same: each individual read of every supporting pairs does map to the 5'gene and none to the 3'gene. I thought that at least for the reads tagged as "supports_fusion_pair" one of the mates should have a very good alignment to the 3'gene but this is not the case which makes me wonder why fusioncatcher thinks they support the fusion event.
I guess the conclusion from these observations is anyways that the fusion is a false positive so I will close this issue.
Thanks again for your time.

**Comment by ndaniel** [comment]
What about mapping the fusion junction using BLAT in UCSC Genome browser? How does the look?

**Comment by ndaniel** [comment]
It is a little bit challenging what is going on without the reads sequences. It might be a bug in FC or maybe the genes are challenging (like for example if a gene has a large number of pseudogene which have a high similarity sequence then all the aligners will have a big problem on mapping reads on the given gene because all the reads will map first on its pseudogenes first => it will look like no reads map on the gene of interest).

**Comment by tb08** [comment]
The fusion junction sequence reported by FC is : 
`ACCTGTAGTCCCAGCTACTTGAGAGGCTGAGGCAGGAGAATCGCTTGAAC*CCGGGAGGCAGAGGTTGCAGTGTGGTGAGATCATGCCACTACACTCCAGC`
The entire sequence maps to the 5' gene on chromosome 3, with only a few mismatches on on the right part of the sequence.
If I BLAT separately both parts: the left part of the sequence maps perfectly to the 5' gene on chromosome 3, the right part actually maps multiple times on chr1 but not chr9 where the 3' gene is located.
I attach to this post the file containing all supporting reads.
[PAX5--TNFSF10__36977626--172505821_reads.txt](https://github.com/ndaniel/fusioncatcher/files/3635312/PAX5--TNFSF10__36977626--172505821_reads.txt)
