### ISSUE TITLE
Incorrect fusion coordinate in BCL2

### ISSUE THREAD

**Issue by maressyl** [ndaniel/fusioncatcher#157]
Hi again,

Still investigating our fusion results, I faced one which seems legit but whose fusion coordinates and sequence are problematic.

When aligning supporting reads to GRCh38 with STAR the breakpoint is quite obvious at the very end of BCL2 (reads facing left) and at the 5' of IGHG1 (reads facing right), however the breakpoint is reported at `18:63223954:-` in BCL2 (middle of the intron right from the read cluster). I have the feeling fusionCatcher was looking for an intron but failing to find one downstream the read cluster, it picked on upstream which is incorrect.

BLATing the fusion sequence reported by fusionCatcher gives the same coordinates, so I don't think it is the same problem as reported earlier with SPOTLIGHT.

IGV screenshots, supporting read archive and tabular extract are available below.

Best regards,
Sylvain

![BCL2](https://user-images.githubusercontent.com/4406719/76098161-40e47280-5fc9-11ea-954f-195ffb623160.png)
![BCL2_zoom](https://user-images.githubusercontent.com/4406719/76098175-480b8080-5fc9-11ea-86c6-c898024cf8ed.png)
![IGHG1](https://user-images.githubusercontent.com/4406719/76098187-4c379e00-5fc9-11ea-8bef-e72378561349.png)

[BCL2--IGH_locus_(g)__63223954--105743073_reads.STAR.zip](https://github.com/ndaniel/fusioncatcher/files/4299124/BCL2--IGH_locus_.g.__63223954--105743073_reads.STAR.zip)

Gene_1_symbol.5end_fusion_partner. | Gene_2_symbol.3end_fusion_partner. | Fusion_description | Counts_of_common_mapping_reads | Spanning_pairs | Spanning_unique_reads | Longest_anchor_found | Fusion_finding_method | Fusion_point_for_gene_1.5end_fusion_partner. | Fusion_point_for_gene_2.3end_fusion_partner. | Gene_1_id.5end_fusion_partner. | Gene_2_id.3end_fusion_partner. | Exon_1_id.5end_fusion_partner. | Exon_2_id.3end_fusion_partner. | Fusion_sequence | Predicted_effect
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BCL2 | IGH@ | known,oncogene,chimerdb2,chimerdb3kb,cancer,tumor,m83 | 0 | 254 | 3 | 17 | BOWTIE+STAR | 18:63223954:- | 14:105743073:- | ENSG00000171791 | ENSG09000001013 |   |   | TTTTTTTTCTTTTCAGAAATTGTCTTTGCCTCTCCTGGTCTCTGTCTCCT*CAGCCTCCACCAAGGGCCCATCGGTCTTCCCCCTGGCACCCTCCTCCAAG | intronic/---

**Comment by ndaniel** [comment]
Hi @maressyl 

IGH fusions are very challenging to find because IGH genes have high variability between people. That means that all the sequence variability is not captured almost at all in the current gene annotations (eg. genecode, Ensembl, etc.). Because of this IGH fusions genes are very challenging to find in RNA-seq data. As far as I know FusionCatcher is the only fusion caller that is freely available that is able to consistently call IGH fusion genes.

One observations is that FusionCatcher actually calls BCL2-IGH@ where IGH@ is IGH locus (that is the region where re most of the IGH genes located on genome). It just happens that IGHG1 is overlapping there where the fusion is. FusionCatcher sees IGH@ locus as one big gene which supersedes all IGH genes (because the IGH gene annotation is full with errors). Therefore IGH part of the fusion BCL2-IGH@ looks ok to me.

Regarding, the BCL2 here are some observations:
- FusionCatcher used STAR to align the reads on BCL2 gene  alone and not the entire genome (when mapping reads on one gene at a time the mapping of reads can be quite different than mapping on entire genome and then looking to that gene)
- FusionCatcher uses Ensembl gene annotation and not Genecode

.....

**Comment by maressyl** [comment]
Hi @ndaniel,

Thanks for your answer.

> As far as I know FusionCatcher is the only fusion caller that is freely available that is able to consistently call IGH fusion genes.

Indeed, that's a reason why I find it very interesting !

> Therefore IGH part of the fusion BCL2-IGH@ looks ok to me.

I agree on that, I'm only concerned about the breakpoint location in BCL2 for this case.

> FusionCatcher used STAR to align the reads on BCL2 gene  alone and not the entire genome (when mapping reads on one gene at a time the mapping of reads can be quite different than mapping on entire genome and then looking to that gene)

Actually I did too (the breakpoint location is important for me because I realign both to the full gene and to a chimeric genome built from fusionCatcher's coordinates), the results were very similar.

> FusionCatcher uses Ensembl gene annotation and not Genecode

Later versions of Genecode mostly rely on Ensembl transcripts, I don't expect big differences, especially in a gene as well characterized as BCL2.

> When looking to the evidence for BCL2-IGH@ fusion that FusionCatcher provides I would say that very likely the fusion BCL2-IGH@ is real (because there are 254 pair of reads the supports it) BUT probably FusionCatcher found the wrong fusion junction (because it found only 3 reads that map over the fusion junction that is the minimum value for the threshold if there would have been 2 reads then this fusion would not have been reported).

I agree, however I was using BCL2-IGH@ fusions as positive controls to better assess other fusions with lower levels of evidence, I'm a bit worried to find errors there, because if the breakpoint coordinates are not reliable I must find another way to visually assess fusion candidates. I'm even more worried to find the discrepancy on the BCL2 side, as you write IGH@ is quite complex so I would not have been surprised to see fusionCatcher struggle there.

> For some reason I would have expected that SPOTLIGHT method would have reported this fusion because SPOTLIGHT was created exactly for this kind of cases.

Actually fusionCatcher reported 4 breakpoints for BCL2 / IGH@ in this sample :

Gene_1_symbol.5end_fusion_partner. | Gene_2_symbol.3end_fusion_partner. | Fusion_description | Counts_of_common_mapping_reads | Spanning_pairs | Spanning_unique_reads | Longest_anchor_found | Fusion_finding_method | Fusion_point_for_gene_1.5end_fusion_partner. | Fusion_point_for_gene_2.3end_fusion_partner. | Gene_1_id.5end_fusion_partner. | Gene_2_id.3end_fusion_partner. | Exon_1_id.5end_fusion_partner. | Exon_2_id.3end_fusion_partner. | Fusion_sequence | Predicted_effect
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BCL2 | IGH@ | known,oncogene,chimerdb2,chimerdb3kb,cancer,tumor,m83 | 0 | 254 | 3 | 17 | BOWTIE+STAR | 18:63223954:- | 14:105743073:- | ENSG00000171791 | ENSG09000001013 |   |   | TTTTTTTTCTTTTCAGAAATTGTCTTTGCCTCTCCTGGTCTCTGTCTCCT*CAGCCTCCACCAAGGGCCCATCGGTCTTCCCCCTGGCACCCTCCTCCAAG | intronic/---
BCL2 | IGH@ | known,oncogene,chimerdb2,chimerdb3kb,cancer,tumor | 0 | 41 | 3 | 35 | BOWTIE+STAR | 18:63126258:- | 14:105864254:- | ENSG00000171791 | ENSG09000001014 |   |   | CTCATGGCTGTCCTTCAGGGTCTTCCTGAAATGCAGTGGTGCTTACGCTC*NNNNNNNNNNNNNNNNNNNNNGACTACTGGGGCCAGGGAACCCTGGTCACCGTCTCCTCAGGTGAGTCCTC | UTR/---
BCL2 | IGH@ | known,oncogene,chimerdb2,chimerdb3kb,cancer,tumor | 0 | 41 | 2 | 86 | BOWTIE+SPOTLIGHT | 18:63126258:- | 14:63188185:- | ENSG00000171791 | ENSG09000001014 |   |   | CCCAGAGCCCTCCTGCCCTCCTTCCGCGGGGGCTTTCTCATGGCTGTCCTTCAGGGTCTTCCTGAAATGCAGTGGTGCCTACGGAC*GGACCGACTACTGGGGCCAGGGAACCCTGGTCACCGTCTCCTCAGGTGAGTCCTCACAACCTCTCTCCTGCTTTAACTCTGAAGGGTTTTGCTGCATTTTTGGGGGGAAATAAGGGTGCTGGGTCTCCTGCC | UTR/---
BCL2 | IGH@ | known,oncogene,chimerdb2,chimerdb3kb,cancer,tumor | 0 | 41 | 2 | 34 | BOWTIE+STAR | 18:63126261:- | 14:105863858:- | ENSG00000171791 | ENSG09000001014 |   |   | TTTCTCATGGCTGTCCTTCAGGGTCTTCCTGAAATGCAGTGGTGCTTACG*NNNNNNNNNNNNNNNNNNNNNGGTTCGACCCCTGGGGCCAGGGAACCCTGGTCACCGTCTCCTCAGGTGAG | UTR/---

There is indeed a SPOTLIGHT breakpoint, but for this one I faced the problem I reported in another issue with the breakpoint coordinates (#115). The breakpoint discussed in the present issue was however the one with higher evidence level, the second one is correctly located by fusionCatcher but with much lower evidence, and considering the reads align somewhere else in IGH@ I don't think they rely on the same reads.

By the way I struggled to find what this SPOTLIGHT software is, is it a specific aligner ?


Best,
Sylvain

**Comment by ndaniel** [comment]
Hello @maressyl 

SPOTLIGHT is not a software. Sorry, that this is not explained in the documentation. SPOTLIGHT is a method that I cooked up for finding very challenging IGH fusions. SPOTLIGHT does shortly this in this order:
1) merge the paired-end reads (that do not align or aligned badly on the genome/transcriptome),
2) align the merged paired-ends using BBMAP aligner (on of the sequence of the two genes that form the candidate fusion) 
SPOTLIGHT can handle better IGH fusions where is a random sequence (ie. I cannot figure out from where this random sequences come from because they are quite short) inserted at the fusion junction, which from what I have seen it occurs more often than one would expect in IGH fusions. This means that an IGH fusion looks many times like this `IGH-random_sequence-BCL2`. Also SPOTLIGHT has limitations like for example it cannot handle random sequences longer than 25 bp. 

FusionCatcher signals that there is a random sequence inserted at the fusion junction by using this "*NNN" (the number of Ns is always constant and it does not reflect the length of the random sequence). SPOTLIGHT in many situations can figure out the random sequence that is inserted at the fusions junction. For example, if one aligns this fusions sequence found by SPOTLIGHT `CCCAGAGCCCTCCTGCCCTCCTTCCGCGGGGGCTTTCTCATGGCTGTCCTTCAGGGTCTTCCTGAAATGCAGTGGTGCCTACGGAC*GGACCGACTACTGGGGCCAGGGAACCCTGGTCACCGTCTCCTCAGGTGAGTCCTCACAACCTCTCTCCTGCTTTAACTCTGAAGGGTTTTGCTGCATTTTTGGGGGGAAATAAGGGTGCTGGGTCTCCTGCC` using Blat in UCSC Genome Browser will see this nicely (where region 1-83 maps on gene BCL2, region 92-218 maps on gene IGH locus, region 84-91 is some random DNA sequence).

As I highlighted above the IGH fusions are very different than other non-IGH fusions. Also th IGH fusions can be quite different among themselves because some have random inserts and others do not have. Different algorithms are used by FusionCatcher to find the IGH fusions and therefore I think that they are not really comparable because an IGH fusion with a 20 bp random insert is several magnitudes more difficult to find that a IGH fusion without any random insert sequence and which follows nicely the exon and the introns. The more challenging is an IGH fusion the less evidence FusioonCatcher will find.

So, when looking to all information that is provided above I would say that very likely the IGH-BCL2 fusion is real but unfortunately FusionCatcher is not really able to find the fusion junction points (ie. FusionCatcher finds some fusion junction points but I think that those are errors). My gut feeling is that here the random sequence that is inserted at the fusion junction IGH-BCL2 is much longer than what FusionCatcher can handle.

In order to improve FusionCatcher I would need the *real* fusion sequence of IGH-BCL2 in this case but in this case it is not known. :-(
