### ISSUE TITLE
FusionCatcher misses a KMT2A-AFF1 fusion

### ISSUE THREAD

**Issue by tom-sober** [ndaniel/fusioncatcher#161]
Hi Daniel,

I have run `fusioncather` on RNAseq data from 6 leukemia patients, all of whom I know have KMT2A fusions (confirmed by RT-PCR: three KMT2A-AFF1, two KMT2A-MLLT1, and one KMT2A-MLLT3 cases).
`FusionCather` identifies KMT2A fusions in 5 of the 6 samples, but misses a KMT2A-AFF1 fusion in one case, though `kallisto/pizzly` successfully identifies all KMT2A fusions (Read counts by pizzly for the KMT2A-AFF1 fusion which fusioncatcher missed were `paircount = 0` and `splitcount = 1`).

So far I prefer `fusioncatcher` in some respects such as fusion frame classification and junction coordinates, which are not provided by `pizzly`, so I wonder whether `fusioncatcher` will be able to identify the KMT2A-AFF1 fusion in this sample after modifying some pipeline options/parameters?

Thanks,
Tom

**Comment by ndaniel** [comment]
Hi @tom-sober 

FusionCatcher will never call a fusion which has `paircount = 0` and `splitcount = 1` because the false-positives would go thru the roof. FusionCatcher would need at least `paircount = 1` and `splitcount = 2` in order to call a fusion. Below that FusionCatcher just does not work.

I would say that indeed if the fusion has  `paircount = 0` and `splitcount = 1`  then probably the sample has not been sequenced deep enough. Increasing the number of reads might help with avoiding this kind of situation.

Cheers,
Daniel

**Comment by tom-sober** [comment]
Hi Daniel,

My apologies for the delayed response.
Yes, including such fusions with only `paircount = 0` and `splitcount = 1` will result in lots of false positives. But because those reads counted are the ones successfully aligned to the transcriptome, and because the difficulty in calling KMT2A fusion is caused by micro-exons of fusion partner genes (in this case, AFF1), I wonder whether the KMT2A-AFF1 fusion could be called (more raw fusion reads could be successfully mapped) after properly adjusting the alignment-related parameters.
Indeed, in another sample with KMT2A-MLLT1, `fusioncatcher` calls the fusion with `Spanning_pairs = 1` and `Spanning_unique_reads = 2`, for which `kallisto + pizzly` identifies only `paircount = 0` and `splitcount = 2`.

Do you have any ideas of which parameters to be changed and how?

Thanks,
Tom

**Comment by ndaniel** [comment]
Hi @tom-sober,

so FusionCatcher really needs `paircount >0` because this is the starting point for FusionCatcher. Basically, FusionCatcher evaluates all the candidates fusions, one by one, which have `paircount >0`.
This is the design of FusionCatcher.

Now, FusionCatcher and other fusion callers, like Pizzly, have slightly different definition of `paircount` (and also how the read are trimmed/processed/etc. before the alignment). This is the explanation of why FusionCatcher says `paircount = 1` whilst Pizzly says `paircount=0`.

FusionCatcher and Pizzly are looking for all fusions in the input RNA-seq data. Therefore they use [unsupervised learning](https://en.wikipedia.org/wiki/Unsupervised_learning) approach.

If one looks **only and only** for KMT2A fusions in an input RNA-seq then probably a [supervised learning](https://en.wikipedia.org/wiki/Supervised_learning) approach would be more suitable. Supervised approaches perform better than unsupervised one in general but supervised approaches cannot be applied everywhere.

**Comment by tom-sober** [comment]
Hi Daniel,

Thank you for the detailed explanation. I think the best solution in this situation would be to re-sequence the sample and get more sequencing depths as you suggested earlier...

Thanks,
Tom

**Comment by ndaniel** [comment]
Indeed re-sequencing with more depth would definitely would help all the fusions callers.
