### ISSUE TITLE
further parallelization

### ISSUE THREAD

**Issue by anoronh4** [ndaniel/fusioncatcher#162]
I recently discovered the `--parallel` parameter that is mentioned in passing in the fusioncatcher detailed manual. I think this should be mentioned in the help menu of fusioncatcher (I see that it is not), but my question is, would it be further useful to run multiple instances of fusioncatcher with each alternative aligner and then later merge them? or is that redundant given how the `--parallel` option works? if i were to separate different aligners, is there a way to merge them in a way that would produce exactly what fusioncatcher would produce with all the aligners on in the same instance?

also, is `--parallel` turned on by default (how about when i'm already using -p to turn on multi-threading)?

**Comment by anoronh4** [comment]
actually i now see that --parallel is not longer a valid parameter in fusioncatcher (even though it's still mentioned in the main script). Is that a bug? If not, my other question remains:
would it be useful to run multiple instances of fusioncatcher with each alternative aligner and then later merge them? is there a way to merge them in a way that would produce exactly what fusioncatcher would produce with all the aligners on in the same instance?

**Comment by ndaniel** [comment]
Hello @anoronh4 

I am not sure what you are referring to by `--parallel`.

FusionCatcher has the command line option `--threads/-p` in order to allow the user to specify the number of processes to be used by FusionCatcher. FusionCatcher is a just a pipeline that runs other software tools, like Bowtie, STAR, Blat, sort, Seqtk etc. Whenever possible FusionCatcher will pass to the software tools the processes which should be used but some tools to not support to run in parallel mode and therefore FusionCatcher cannot do too much about that.

Indeed, one looks to `fusioncatcher.py` code there shows up `--parallel` but that is for `sort` only.

> would it be useful to run multiple instances of fusioncatcher with each alternative aligner and then later merge them? is there a way to merge them in a way that would produce exactly what fusioncatcher would produce with all the aligners on in the same instance?

This would not be possible because the aligners depend on the run of the previous aligner. For example, STAR needs the results of the alignment from Bowtie, and BBMAP needs the alignment results from STAR and so on.

**Comment by anoronh4** [comment]
is there any way to give fusioncatcher alignment outputs from bowtie and STAR, etc? that way we can process them in parallel on our own. We're very interested in decreasing total run-time.

**Comment by ndaniel** [comment]
The only way I can think of helping FusionCatcher to run faster is to remove the reads from the input FASTQ files which for sure are not part of any fusion.

```
bowtie \
--seed 1234 \
-t \
--seedmms 1 \
--seedlen 33 \
-X 10000 \ 
-p 1 \
-k 1 \
--un filtered.fq \
--max /dev/null \
transcripts_index \
-1 r1.fq \
-2 r2.fq \
/dev/null
```

Here the input files are `r1.fq` and `r2.fq` and after filtering the files that contain the reads that should be fed to FusionCatcher are `filtered_1.fq` and `filtered_2.fq`. The trick here is that the paired end reads that map on transcriptome (ie. transcripts_index) less than 10 000 bp (this is specified using -X) apart are written to /dev/null and the paired end reads that do not fulfill this condition are written into filtered_1.fq and filtered_2.fq (and these are needed by FusionCatcher).  

Anyway, along this line.

eXpress is doing something similar but on reverse (see: https://hpc.nih.gov/apps/express.html )

**Comment by anoronh4** [comment]
thanks, i'll look into this!
