### ISSUE TITLE
Incorrect Coordinate for one fusion partner in otherwise valid fusion

### ISSUE THREAD

**Issue by AlinaMH** [ndaniel/fusioncatcher#169]
Hi, 
I have a problem that is somewhat similar to the ones reported in issue #157 and #115 
We run fusioncatcher on a large cohort (> 600 samples) with RNAseq data from leukemic bone marrow. 
In some cases we find a fusion that is valid, where fusion partners and break coordinates are in accordance with published recurrent fusions. In addition to the correct fusion gene prediction, fusioncatcher outputs an incorrect fusion gene coordinate.
We are using fusioncatcher **v1.20**

Here are some examples: 
Fusioncatcher calls EP300-ZNF384 to chr22:**41131633** and chr12:**6679525**  **correctly** in two cases (line 2 and 3, see below). 
But in two cases, the 3'-position is called as  chr12:**41105261** (line 1 and 5) which, when looking it up in the genome is very far away from ZNF384, in fact it's an intergenic position somewhere close to the centromere. 
However, 
1) the fusion sequences for ZNF384 are identical for the called fusions
2) the position (but not chromosome number) for the intergenic, way-off fusion is similar to the position of the 5'-gene 

```
EP300	ZNF384	known,chimerdb3pub,cancer	7	118	78	138	BOWTIE+SPOTLIGHT	22:41131633:+	12:41105261:-	ENSG00000100393	ENSG00000126746			GACAACAGTCTGCCCCCAACCTAAGCACTGTTAGTCAGATTGATCCCAGCTCCATAGAAAGAGCCTATGCAGCTCTTGGACTACCCTATCAAGTAAATCAGATGCCGACACAACCCCAGGTGCAAGCAAAGAACCAGCAGAATCAGCAGCCTGGGCAGTCTCCCCAAGGCATGCGGCCCATGAGCAACATGA*GTAGAATGGAAGAATCTCACTTCAATTCTAACCCGTACTTCTGGCCTTCTATCCCCA	CDS(truncated)/intergenic	EP300_ZNF384	EP300_ZNF384	ZNF384	EP300_ZNF384	ZNF384
EP300	ZNF384	known,chimerdb3pub,cancer,exon-exon	7	118	26	30	BOWTIE;BOWTIE+STAR	22:41131633:+	12:6679525:-	ENSG00000100393	ENSG00000126746	ENSE00001336414	ENSE00003617657	CCTGGGCAGTCTCCCCAAGGCATGCGGCCCATGAGCAACATGA*GTAGAATGGAAGAATCTCACTTCAATTCTAACCCGTACTTCTG	CDS(truncated)/UTR	EP300_ZNF384	EP300_ZNF384	ZNF384	EP300_ZNF384	ZNF384
EP300	ZNF384	known,chimerdb3pub,cancer,exon-exon	7	118	8	29	BOWTIE	22:41130003:+	12:6679525:-	ENSG00000100393	ENSG00000126746	ENSE00000655024	ENSE00003617657	TGTCTCCCCCTCAAAAATGCTGGTGATAAGAGAAATCAACAGC*GTAGAATGGAAGAATCTCACTTCAATTCTAACCCGTACTTCTG	CDS(truncated)/UTR	EP300_ZNF384	EP300_ZNF384	ZNF384	EP300_ZNF384	ZNF384
EP300	ZNF384	known,chimerdb3pub,cancer,exon-exon	7	118	4	27	BOWTIE	22:41131633:+	12:6679521:-	ENSG00000100393	ENSG00000126746	ENSE00001336414	ENSE00002288098	CCTGGGCAGTCTCCCCAAGGCATGCGGCCCATGAGCAACATGA*AATGGAAGAATCTCACTTCAATTCTAACCCGTACTTCTGGCCT	CDS(truncated)/UTR	EP300_ZNF384	EP300_ZNF384	ZNF384	EP300_ZNF384	ZNF384
EP300	ZNF384	known,chimerdb3pub,cancer	7	118	3	66	BOWTIE+SPOTLIGHT	22:41130003:+	12:41105261:-	ENSG00000100393	ENSG00000126746			TGAGGCAGTGCAACCTTCCCCACTGTCGCACAATGAAGAATGTCCTAAACCACATGACACACTGCCAGTCAGGCAAGTCTTGCCAAGTGGCACACTGTGCATCTTCTCGACAAATCATTTCACACTGGAAGAATTGTACAAGACATGATTGTCCTGTGTGTCTCCCCCTCAAAAATGCTGGTGATAAGAGAAATCAACAGC*GTAGAATGGAAGAATCTCACTTCAATTCTAACCCGTACTTCTGGCCTTCTATCCCCA	CDS(truncated)/intergenic	EP300_ZNF384	EP300_ZNF384	ZNF384	EP300_ZNF384	ZNF384



```

We find the same issue in other fusions with a similar pattern
- presumably correctly called fusion with positions matching the fusion partners 
- additional fusion called with identical fusion partners and sequence but with way off position for one fusion partner that looks like there was a mix-up of positions (but not chromosome numbers) resulting in an output coordinate that is somwhere way off from the called gene 

Here's another example from a different sample and with different fusion partners (IGH@ -- CEBPE)

```
IGH@	CEBPE	known	0	685	249	121	BOWTIE+SPOTLIGHT	14:105864261:+	14:105780920:-	ENSG09000000014	ENSG00000092067			TTCAGAGTTAAAGCAGGAGAGAGGTTGTGAGGACTCACCTGAGGAGACGGTGACCAGGGTTCCCTGGCCCCAGTAGTCAAAGTAG*TGGAGTCCCCTGGGCTCCCAGCAGGGAGTGGAGAGGCATTCCCAGAAGCATCAGCTTCGGGCATCTCCAGAACCCTGGCTTGG	---/intergenic	BCL2_IGH@;BCL6_IGH@;CEBPE_IGH@;CRLF2_IGH@;DUX4_IGH@;EPOR_IGH@;MYC_IGH@;CEBPA_IGH@	IGH@_CEBPE	BCL2/MYC;CEBPE;PAX5alt/Ph-like;DUX4;Ph-like;CEBPA	CEBPE_IGH@	CEBPE
IGH@	CEBPE	known	0	685	37	38	BOWTIE+STAR	14:105864261:+	14:23119535:-	ENSG09000000014	ENSG00000092067			CACCTGAGGAGACGGTGACCAGGGTTCCCTGGCCCCAGTAGTCAAAGTAG*TGGAGTCCCCTGGCCTCCCAGCAGGGAGTGGAGAGGCATTCCCAGAAGCA	---/UTR	BCL2_IGH@;BCL6_IGH@;CEBPE_IGH@;CRLF2_IGH@;DUX4_IGH@;EPOR_IGH@;MYC_IGH@;CEBPA_IGH@	IGH@_CEBPE	BCL2/MYC;CEBPE;PAX5alt/Ph-like;DUX4;Ph-like;CEBPA	CEBPE_IGH@	CEBPE

```

And another one with IGH@ -- CLRF2 (where fusion genes are not on the same chromosome) 

```
IGH@	CRLF2	known,oncogene,cancer,m7	0	11	4	36	BOWTIE+STAR	14:105856217:+	X:1205333:-	ENSG09000000014	ENSG00000205755			GGAATTCTCACAGGAGACGAGGGGGAAAAGGGTTGGGGCGGATGCACTCC*CTTCAGTTACTTTCAGTTAAGTTCTGAAAATCAAGCTCATGGACCATTGG	---/intronic	BCL2_IGH@;BCL6_IGH@;CEBPE_IGH@;CRLF2_IGH@;DUX4_IGH@;EPOR_IGH@;MYC_IGH@;CEBPA_IGH@	IGH@_CRLF2	BCL2/MYC;CEBPE;PAX5alt/Ph-like;DUX4;Ph-like;CEBPA	CRLF2_IGH@	PAX5alt/Ph-like
IGH@	CRLF2	known,oncogene,cancer,m7	0	11	2	133	BOWTIE+SPOTLIGHT	14:105856216:+	X:105822667:-	ENSG09000000014	ENSG00000205755			GCTCCCTCTCAGGACTGATGGGAAGCCCCGGGTGCTGCTGATGTCAGAGTTGTTCTTGTATTTCCAGGAGAAAGTGATGGAGTCGGGAAGGAAGTCCTGTGCGAGGCAGCCAACGGCCACGCTGCTCGTATCCGACGGGGAATTCTCACAGGAGACGAGGGGGAAAAGGGTTGGGGCGGATGCACTC*CCTTCAGTTACTTTCAGTTAAGTTCTGAAAATCAAGCTCATGGACCATTGGCCACTAGAGCCCGGTGCCC	---/intergenic	BCL2_IGH@;BCL6_IGH@;CEBPE_IGH@;CRLF2_IGH@;DUX4_IGH@;EPOR_IGH@;MYC_IGH@;CEBPA_IGH@	IGH@_CRLF2	BCL2/MYC;CEBPE;PAX5alt/Ph-like;DUX4;Ph-like;CEBPA	CRLF2_IGH@	PAX5alt/Ph-like
IGH@	CRLF2	known,oncogene,cancer,m7	0	11	2	41	BOWTIE+STAR	14:105856217:+	X:1235587:-	ENSG09000000014	ENSG00000205755			GGAATTCTCACAGGAGACGAGGGGGAAAAGGGTTGGGGCGGATGCACTCC*TTCCCAGATGGGGTGGCTGCCGGGCGGAGAGGCTCCTCACTTCTCAGATG	---/intergenic	BCL2_IGH@;BCL6_IGH@;CEBPE_IGH@;CRLF2_IGH@;DUX4_IGH@;EPOR_IGH@;MYC_IGH@;CEBPA_IGH@	IGH@_CRLF2	BCL2/MYC;CEBPE;PAX5alt/Ph-like;DUX4;Ph-like;CEBPA	CRLF2_IGH@	PAX5alt/Ph-like
```

Two more observations, we do not seem to get this error for fusions with very well characterized fusion proteins (like BCR-ABL1) and it looks like these faulty positions are always called by BOWTIE+SPOTLIGHT 

Do you have any idea where these positions might come from? We are using the positions for downstream analysis and are wondering how we can filter the incorrect ones out without missing out real fusions. 

Kind regards, 
Alina

**Comment by ndaniel** [comment]
Hello Alina,

FusionCatcher "extends" genes from a custom set of genes, like for example ZNF384. Therefore when FusionCatcher finds a fusion of ZNF384 will most likely give a coordinate that falls into a intergenic region but still should be close to ZNF384.

Regarding IGH@ (which actually is a region on chromosome and not a gene) the things are even more complicated. Very likely most of the IGH@ fusions that FusionCatcher reports will have coordinate that falls intergenic regions but between IGH genes. As far as I know only FusionCatcher is able to find IGH fusions.

Anyway, all these do not affect the goodness of those fusions. These are just methods used by FusionCatcher to find fusions.
So, most likely the genomic coordinates are good just that they do no correspond very well with the "current" known gene positions. In time the gene annotation databases (eg. GeneCode, Ensembl, RefSeq, etc.) update themselves and in time tthsoe intergenic coordiantes end up being inside the genes. Many of these custom changes that FusionCatcher uses to "extend" the genes I submit also to gene annotation databases and many times they accept.

In general, BOWTIE+SPOTLIGHT is used by FusionCatcher when very challenging fusion genes are detected like for example IGH@ fusions. The downside is that BOWTIE+SPOTLIGHT is good at detecting very challenging fusions BUT it might have trouble in detecting exactly the fusion coordinate (or it gives a very approximate fusion coordinate). This does not mean that the fusion which was detected is not good. It just means that BOWTIE+SPOTLIGHT finds very challenging to give an exact fusion coordinate (because some fusions have inserted random DNA sequence of 10-20bp long at the fusion junction and this throw off badly the aligners).

The signal for the fusions IGH@-CEBPE and EP300-ZNF384 looks very strong to me.

The support for IGH@-CRLF2 is not that great. BUT here one could use the information about the sample and cancer from which the samples is coming from. For example, If I remember right IGH@-CRLF2 fusion is known to be found mostly in leukemias and/or lymphomas. So if there it is not leukemia/lymphoma then probably the fusion is a false positive.

Cheers,
Daniel

**Comment by AlinaMH** [comment]
Hello Daniel, 
thank you for your fast reply. 
What you describe here 

> FusionCatcher "extends" genes from a custom set of genes, like for example ZNF384. Therefore when FusionCatcher finds a fusion of ZNF384 will most likely give a coordinate that falls into a intergenic region but still should be close to ZNF384.

is not really what we see however. The intergenic position that fusioncatacher reports is more than 30 Megabases away from the correct position and nowhere near ZNF384. 
The same holds true for the IGH@ fusions, I am aware that positions might differ a little bit, but the reported positions are half a chromosome away from the gene (see example for IGH@--CRLF2). 
That, and the fact that the numeric part of the coordinate always looks very similar to the numeric part of the fusion partner's coordinate led us to wonder if there might be some mix-up happening when fusioncatcher outputs coordinates. 
When we blast the fusion sequence, we end up in the reported gene but nowhere near the reported coordinate. So I think the fusions are indeed correct, but the reported coordinate is mixed up. 

I don't really know how to phrase it better, do you know what I mean? 
Kind regards, 
Alina

**Comment by AlinaMH** [comment]
Hi Daniel , 
sorry for the larte reply. Thanks for looking into the bug! For our samples we manually checked coordinates for now and it looks like the fusions are generally valid. 
Kind regards, 
Alina

**Comment by ndaniel** [comment]
:-)

**Comment by rdmorin** [comment]
I'm running 1.35 and confirm this bug still exists. It's specific to fusions from BOWTIE+SPOTLIGHT. The coordinate for one of the partners is consistently mis-reported. 

```
BCL2	IGH@	BOWTIE+SPOTLIGHT	18:63126262:-	14:63186983:-  <- here the position is erroneous and probably refers to the chromosome 18 coordinate in BCL2 rather than the partner coordinate in IGH
BCL2	IGH@	BOWTIE+BLAT;BOWTIE+STAR	18:63127456:-	14:105856217:-
BCL2	IGH@	BOWTIE+BLAT;BOWTIE+STAR	18:63127456:-	14:105845677:-
BCL2	IGH@	BOWTIE+STAR	18:63126265:-	14:105863054:-
```
