### ISSUE TITLE
Old references

### ISSUE THREAD

**Issue by matq007** [ndaniel/fusioncatcher#180]
Hi @ndaniel,

I wanted to ask if it's possible to publish the old references for older versions of FusionCatcher. In [nf-core/rnafusion](https://github.com/nf-core/rnafusion/issues/173) we are still using `human_v98`. I understand that you probably only publish the latest reference due to the size limitation on sourceforge? 
Thank you, Martin

**Comment by ndaniel** [comment]
Personally, I deleted human_v98 because lack of space on my computers. Also I deleted human_v98 from sourceforge due to space limitation.

Basically, I do not have disk space to store older versions of human_v??. BUT if someone offers a public place where to store them in the future I would be happy to put them there in the future.
