### ISSUE TITLE
Single-cell, short read advice

### ISSUE THREAD

**Issue by tantrev** [ndaniel/fusioncatcher#22]
The wiki recommends default options to be used for read lengths that have a minimum length of 35bp (presumably for paired end) and 130bp for single-end.  Unfortunately I have three single-cell RNA-sequencing datasets that do not meet this criteria - one is 25bp paired-end, the second is 50bp single-end, and the third is 125bp single-end.  Do you by chance have any advice on suggested parameters for at least attempting fusion detection using these datasets?  Thank you.

**Comment by ndaniel** [comment]
Regarding, 25bp paired-end I am not sure the FusionCatcher if will be able to find something even that it might run just fine. I have never had in my hands such kind of RNA-seq dataset.
Regarding the 50 bp single-end, FusionCatcher is not able to use it as input.
Regarding the 125 single-end, FusionCatcher should be able to use as input just fine if these command line parameters are used: ``--single-end --sonication 110`.

**Comment by tantrev** [comment]
Thank you for the reply!  Would assembly by chance make a difference for any of the datasets?  I only ask because FusionCatcher's manual briefly mentions its "--assembly" mode and another transcriptome assembler, JAFFA, seems to [tolerate](https://github.com/Oshlack/JAFFA/wiki/HowToSetUpJAFFA) both short reads from both single and paired end runs, as long as assembly is attempted.

**Comment by ndaniel** [comment]
The assembly in FusionCatcher is used just to assemble the reads which already have been found *a priori* by FusionCatcher to map on a fusion gene. Therefore in your case it would help because FusionCatcher.

Finding fusion genes by first doing assembly requires much more reads than finding fusion genes without doing assembly. Therefore finding fusion genes without doing assembly is more sensitive when finding fusion genes. For example, FusionCatcher will find a fusion gene if there are only two pairs of paired-end reads (that is 4 reads altogether) whilst those 4 reads still might not be enough to assemble the fusion gene.
