### ISSUE TITLE
Release Tags

### ISSUE THREAD

**Issue by serverhorror** [ndaniel/fusioncatcher#25]
Hi,
The last release is from Dec. 3rd 2014. Has there been any new version that is stable enough to use?
If so could you please tag those versions so that downstream packages can be build?
Thanks,
Martin

**Comment by ndaniel** [comment]
Hi,

indeed that is correct because the main site for FusionCatcher is SourceForge, where all the tags are properly set.

The latest stable enough is v0.99.6a here: https://sourceforge.net/projects/fusioncatcher/files/fusioncatcher_v0.99.6a.zip
which was released on May 8, 2016 (here is the info: https://github.com/ndaniel/fusioncatcher/blob/master/NEWS ).

I will tag also future releases of FusionCatcher also on GitHub. Unfortunately, FusionCatcher cannot be fully moved for now on GitHub due to GitHub's file size restrictions (for free accounts?).

Cheers,
Daniel

**Comment by serverhorror** [comment]
Hi,
Thanks for the heads up. In that case I think it would be good to make a recognizable note in the README where the main site is, maybe even put it in the Github description?
Thanks,
Martin

**Comment by ndaniel** [comment]
Hi!

Excellent idea to specify that SF is the main site. I will do that!

Daniel
