### ISSUE TITLE
bowtie-build: error while loading shared libraries: libtbbmalloc_proxy.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by danielgerlach** [ndaniel/fusioncatcher#31]
Hi,

I running the FusionCatcher installation script on an Ubuntu 14.04 node (DNAnexus) with these package pre-installed ( build-essential, openjdk-7-jre, python2.7, python2.7-dev, gcc, libghc-zlib-dev, python-numpy, python-biopython, python-xlrd, python-openpyxl, dx-toolkit). All dependencies install nicely, however towards the end I see this error message claiming that a shared library is not found. I am nowmtesting to install libtbb2 to see if this fixes the problem.

`bowtie-build: error while loading shared libraries: libtbbmalloc_proxy.so.2: cannot open shared object file: No such file or director`

Daniel

**Comment by ndaniel** [comment]
Hi,

so it looks like it might be an issue specific to Bowtie 1.2 which was introduce into FusionCatcher v0.99.7b! FusionCatcher v0.99.7a still uses Bowtie 1.1.2.

I am not sure exactly how I could help here! Maybe reporting the bug to Bowtie1.2 might help: https://github.com/BenLangmead/bowtie/issues

Cheers,
Daniel

**Comment by ndaniel** [comment]
Does this help?
```
sudo apt-get install libtbb-dev
```

**Comment by yhoogstrate** [comment]
Such linking errors are exactly thre reason this issue was reported: https://github.com/ndaniel/fusioncatcher/issues/20

**Comment by ndaniel** [comment]
Hi yhoogstrate!

Have you met personally this issue?

Cheers,
Daniel

**Comment by yhoogstrate** [comment]
Hi there @ndaniel ,

No I did not experience anything like that and I am also pretty sure that the bowtie and bowtie2 build from your bootstrap can not cause this problem because they are statically linked. But some other software is dynamically linked (ucsc tools, seqtk tools) and they have the potential to cause similar problems unless being used by a package manager that takes care of distributing also the linked libraries. I've seen situations where dynamically linked binaries from old CentOS systems are incompatible with bleeding edge Arch systems because of different glibc versions.
The bootstrap script also allows to compile software from source (https://github.com/ndaniel/fusioncatcher/blob/master/bin/bootstrap.py#L731) for tools that are not providing binaries (velvet?). In Galaxy we have done things that way too and I've seen quite some problems with source dependency management (gcc versions, ncurses present, etc.).
It turned out bio-conda has solved most of these things. It distributes dynamically linked binaries with managing corresponding dependencies and tests running packages on a really bare bone linux distribution.

I think fusioncatcher would benefit from dependency management but I also realize it may be a lot of work. Just take my comments with a grain of salt and see it as a kind suggestion ;). Keep up the great work,

Youri

**Comment by ndaniel** [comment]
I got it now! Thanks!

I looked shortly to bio-conda few days ago. Do you happen to know any example of bio-conda tool which has dependecies to other tools? I mean that examples how to get BWA or BOWTIE are not very useful for me in bringing FusionCatcher on bio-conda.

**Comment by yhoogstrate** [comment]
This is how STAR fusion depends on perl and on bwa:
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/star-fusion/meta.yaml

This is how I did a python wrapper:
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/flaimapper/meta.yaml

This is how for exampe in bowtie dynamically linked libraries are included:
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bowtie/meta.yaml#L27

You just need to set bwa, velvet, etc. as runtime dependency and some python stuff as build dependency, something like this I guess:

```
requirements:
  build:
    - python 
    - biopython
    - setuptools
  run:
    - python
    - biopython
    - setuptools
    - bowtie
    - bowtie2
    - bwa
    - STAR ==2.5.1
```

**Comment by ndaniel** [comment]
Dank je!

Which do you think that is better of these installation:
1)  `conda install fusioncatcher`, or
2)  using `bootstrap.py` to install fusioncatcher, and `bootstrap.py` would install (when specified by a command line parameter like for example `--conda`?) external tools by calling directly bioconda?

**Comment by yhoogstrate** [comment]
Graag gedaan xD,

Adding `--conda` also requires you to program something that obtains anaconda/miniconda, which may be a waste of your time. And users may then end up with multiple conda installations or other unexpected behaviour and come with conda problems to you.
I would keep bootstrap.py at least for now and start testing with `conda install fusioncatcher` as alternative, and don't rush with it until you're really happy with it yourself. You can ping me for help or for testing. Once you're happy with `conda install fusioncatcher`, I would put this as recommended way of doing it on your website/README and explain why.

**Comment by ndaniel** [comment]
Hi!

Here is some preliminary info regarding FusionCatcher in BioConda.

https://github.com/ndaniel/bioconda-recipes/tree/master/recipes/fusioncatcher

Comments and suggestions are welcome!

**Comment by yhoogstrate** [comment]
Are you sure you pushed to ndaniel/master ?

2017-03-02 13:05 GMT+01:00 Daniel Nicorici <notifications@github.com>:

**Comment by ndaniel** [comment]
Yes, but I did a mistake (I put two tools in the same pull request) and removed (see [here](https://github.com/bioconda/bioconda-recipes/pull/3980/commits/89cf1173d19c0dfedfd1a0a1eb075823d340fbdd) ).

**Comment by ndaniel** [comment]
@danielgerlach 

Installing these:
```
sudo apt-get install build-essential
sudo apt-get install libncurses5-dev
sudo apt-get install gcc
sudo apt-get install make
sudo apt-get install cmake
sudo apt-get install zlib-dev
sudo apt-get install wget
sudo apt-get install curl
sudo apt-get install pigz
sudo apt-get install libtbb-dev
sudo apt-get install python-dev
sudo apt-get install python-numpy
sudo apt-get install python-biopython
sudo apt-get install python-xlrd
sudo apt-get install python-openpyxl
```
on a bare bone Ubuntu Linux machine before installing FusionCatcher would make the installation of FusionCatcher much smoother!

**Comment by ndaniel** [comment]
To be more exact this should be installed before installing FusionCatcher

```
sudo apt-get install wget gawk gcc g++ make cmake curl unzip zip tar gzip pigz build-essential libncurses5-dev zlib1g-dev python python-dev python-numpy python-biopython python-xlrd python-openpyxl
```

**Comment by ndaniel** [comment]
The solution is here:
https://github.com/ndaniel/fusioncatcher/issues/40
