### ISSUE TITLE
File reads-ids_clip_bowtie2_psl_r1.fq.0 not found

### ISSUE THREAD

**Issue by danielgerlach** [ndaniel/fusioncatcher#32]
I am running the most recent version of FusionCatcher on a paired-end RNA-seq data set of a cell line with about 50M fragments and a read length of 100bp. Although the test reads were running through successfully, I now see this error message on a real world sample. 

<pre>
////////////////////////////////////////////////////////////////////////////////
  Running: step = 422   Time: 18:07   Date: 2017-03-06 (elapsed time: 0d:5h:10m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/home/dnanexus'
head \
-4 /home/dnanexus/J1055.OCI-Ly3.27232_fusioncatcher/reads-ids_clip_bowtie2_psl_r1.fq.0 \
> /home/dnanexus/J1055.OCI-Ly3.27232_fusioncatcher/reads-ids_clip_bowtie2_psl_unmapped_filtered-0_1_t.fq
--------------------------------------------------------------------------------
+-->EXECUTING...
ERROR: Workflow execution failed at step 422 while executing:
----------------
   head \
   -4 /home/dnanexus/J1055.OCI-Ly3.27232_fusioncatcher/reads-ids_clip_bowtie2_psl_r1.fq.0 \
   > /home/dnanexus/J1055.OCI-Ly3.27232_fusioncatcher/reads-ids_clip_bowtie2_psl_unmapped_filtered-0_1_t.fq
----------------
  * Size '/home/dnanexus/J1055.OCI-Ly3.27232_fusioncatcher/reads-ids_clip_bowtie2_psl_r1.fq.0' = 0 bytes
  * Size '/home/dnanexus/J1055.OCI-Ly3.27232_fusioncatcher/reads-ids_clip_bowtie2_psl_unmapped_filtered-0_1_t.fq' = 0 bytes
Executing second time the same step/command in order to capture error messages (i.e. STDERR)...
-------------------------------------------
head: cannot open '/home/dnanexus/J1055.OCI-Ly3.27232_fusioncatcher/reads-ids_clip_bowtie2_psl_r1.fq.0' for reading: No such file or directory
</pre>

**Comment by ndaniel** [comment]
Hi,

I would need more info, like for example the entire log of this run. Has the first run failed and this is a second run on the same input files?

The above partially log of the run looks weird because the commands "head -4" are run in the very beginning whilst the step count if 422 which indicates that this is not in the beginning of the run. 

Cheers,
Daniel

**Comment by ndaniel** [comment]
Hi,

I would need more info, like for example the entire log of this run. Has
the first run failed and this is a second run on the same input files?

The above partially log of the run looks weird because the commands "head
-4" are run in the very beginning whilst the step count if 422 which
indicates that this is not in the beginning of the run.

Cheers,
Daniel

**Comment by ndaniel** [comment]
Ok. I can confirm that this is indeed a bug in FusionCatcher v0.99.7b.

[Here](https://sourceforge.net/projects/fusioncatcher/files/old/fc0997b.patch) is patch for ´fusioncatcher/bin/fusioncatcher.py´ in order fix this bug. Also FusionCatcher v0.99.7b has been released now such that this bug is fixed.

**Comment by danielgerlach** [comment]
Hi,

This is the first run on the file, as I am running on DNAnexus I always restart any job from the beginning. There are two input files given with the pattern *_R1.fastq.gz and *_R2.fastq.gz - both together in one directory without any other files. This was a run with FusionCatcher v0.99.7b. 

I will re-test the sample on DNAnexus.

Thanks @ndaniel
