### ISSUE TITLE
fusioncatcher looks for bowtie in wrong place

### ISSUE THREAD

**Issue by Jeltje** [ndaniel/fusioncatcher#38]
(root installed) fusioncatcher dies with `Wrong version of BOWTIE found` due to this:

` os.system("bowtie --version | head -1 > '%s'" % (outdir('bowtie_version.txt'),))`

This checks if bowtie is in `$PATH`, not if it is in `~/fusioncatcher/tools/bowtie2`, which is where `~/fusioncatcher/fusioncatcher_v0.99.7b/etc/configuration.cfg` says it is.

The same is probably true for the system call to `fastq-dump` and all subsequent `os.system` calls

I printed `sys.path` right before the check and found:
`/opt/fusioncatcher/fusioncatcher_v0.99.7b/bin:/usr/lib/python2.7:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/local/lib/python2.7/dist-packages/numpy:/opt/fusioncatcher/tools/biopython:/opt/fusioncatcher/bin`

**Comment by ndaniel** [comment]
I know that it looks that way but it really is not. FusionCatcher takes the path from configuration.cfg file and adds them to the $PATH using configuration.py (called as `import configuration`).

If you run manually
```
/opt/fusioncatcher/fusioncatcher_v0.99.7b/tools/bowtie/bowtie
````
what does it show?

I guess that this is related to this https://github.com/ndaniel/fusioncatcher/issues/36 and this https://github.com/ndaniel/fusioncatcher/issues/31 and it looks that the newest version of Bowtie, that is 1.2.0 creates a lot of problems due to weird dependencies.

**Comment by Jeltje** [comment]
Indeed! I had forgotten go add libttb2 to my Dockerfile.
Sorry for the confusion.

**Comment by ndaniel** [comment]
That's ok.

**Comment by ndaniel** [comment]
If you wish you could share the docker files for FusionCatcher and I could put them in FusionCatcher (where you are the author).
