### ISSUE TITLE
seqtk trimfq error

### ISSUE THREAD

**Issue by TomSmithCGAT** [ndaniel/fusioncatcher#4]
When I run the test data with default options I get the error message "trimfq: invalid option -- 'B'". If I add the option --5keep 0 to stop trimfq, everything is OK (so far). I believe the following needs amending:

fusioncatcher.py line 2865.
job.add('-B',options.trim_3end_keep,kind='parameter')

should be?
job.add('-b',options.trim_3end_keep,kind='parameter')

**Comment by ndaniel** [comment]
Actually, it is specified in FusionCatcher documentation that FusionCatcher depends on [SeqTK version 1.0-r68e-dirty](http://github.com/ndaniel/seqtk). This release of SeqTK has the command link option "-B".
See:
  * https://code.google.com/p/fusioncatcher/wiki/Manual
  * https://github.com/ndaniel/fusioncatcher/blob/master/DEPENDENCIES

FusionCatcher may be installed using [bootstrap.py](http://sf.net/projects/fusioncatcher/files/bootstrap.py) which will choose the correct seqtk.

**Comment by TomSmithCGAT** [comment]
Ah ha. Apologies for not reading documentation properly. I used bootstrap.py and installed tools as suggested but seqtk seems to have slipped through the net. I'll install the branch of seqtk you have on your github page and re-run. Will the changes you've implemented in seqtk be included in later updates of Heng Li's seqtk?


________________________________

**Comment by ndaniel** [comment]
> Ah ha. Apologies for not reading documentation properly.

That is ok! ;-)

> I used bootstrap.py and installed tools as suggested but seqtk seems to have slipped through the net. 

I will look into it and I will added a more clear error message when the "-B" parameter is not found by seqtk.

> I'll install the branch of seqtk you have on your github page and re-run. 

Ok.

> Will the changes you've implemented in seqtk be included in later updates of Heng Li's seqtk?

I submitted them to main branch long time ago of SeqTK but my additions/changes/patches have not been accepted.

**Comment by ndaniel** [comment]
> I used bootstrap.py and installed tools as suggested but seqtk seems to have slipped through the net.

I tried to replicate this but I was unable to. The bootstrap.py script is able to detect when there an incorrect version of SeqTK.

Anyway, if this happens again in the future than one may force bootstrap.py to install all the tools (and SeqTK too) by running 
```
boostrap.py -y -t
```

**Comment by TomSmithCGAT** [comment]
Hi Daniel,

Thanks for looking into this. I've cloned your version of seqtk and the pipeline runs fine until it hits an error during the STAR index build which doesn't like the option "--sjdbOverhang" (error message below). It looks like STAR needs the location of a GTF to be specified with "--sjdbGTFfile" in order to build the splice junctions database.

The whole pipeline will run if "--sjdbOverhang" is removed from the STAR parameters, although it looks like STAR is never supplied with a GTF during the alignment either from what I can see. Is this correct? If so, does this not impact on the accuracy of alignment?

Tom

ERROR: Workflow execution failed at step 319 while executing:
----------------
   STAR \
   --sjdbOverhang 100 \
   --genomeChrBinNbits 18 \
   --genomeSAindexNbases 14 \
   --runMode genomeGenerate \
   --runThreadN 8 \
   --genomeDir /ifs/projects/proj047/RNA_Seq/fusions2/test-results3/gene-gene-star/ \
   --genomeFastaFiles /ifs/projects/proj047/RNA_Seq/fusions2/test-results3/gene-gene.fa \
   --outFileNamePrefix /ifs/projects/proj047/RNA_Seq/fusions2/test-results3/gene-gene-star-results/
----------------
  * Size '/ifs/projects/proj047/RNA_Seq/fusions2/test-results3/gene-gene-star/' = 0 bytes
  * Size '/ifs/projects/proj047/RNA_Seq/fusions2/test-results3/gene-gene.fa' = 6394641 bytes
  * Size '/ifs/projects/proj047/RNA_Seq/fusions2/test-results3/gene-gene-star-results/' = 13409 bytes


Executing second time the same step/command in order to capture error messages (i.e. STDERR)...

-------------------------------------------
Jun 25 09:41:00 ..... Started STAR run

EXITING because of FATAL INPUT PARAMETER ERROR: when generating genome without annotations (--sjdbFileChrStartEnd or --sjdbGTFfile options)
do not specify >0 --sjdbOverhang
SOLUTION: re-run genome generation without --sjdbOverhang option

Jun 25 09:41:00 ...... FATAL ERROR, exiting


Dr Tom Smith
CGAT Training Fellow | http://www.cgat.org
MRC Functional Genomics Unit | University of Oxford
+44 1865 285854 | Thomas.Smith2@dpag.ox.ac.uk
________________________________

**Comment by ndaniel** [comment]
Hi Tom!

Again it looks like an incompatible (and older) version of STAR is used! 

Please, check if the version of STAR which is used by FusionCatcher (which can be see in info.txt file from directory /ifs/projects/proj047/RNA_Seq/fusions2/test-results3/ ) matches the version of STAR shown in DEPENDENCIES file (which can be found in the directory where FusionCatcher is installed).

Cheers,
Daniel

**Comment by TomSmithCGAT** [comment]
Hi Daniel,

I installed STAR during the bootstrap.py installation process which is installed in the default location (fusioncatcher/tools/star/source) and the configuration file for fusioncatcher points to here.

When fusioncatcher runs command line tools, does it specify the whole path (eg ../fusioncatcher/tools/star/source/STAR) or just use the tool name. I ask because I also have STAR (v 2.4.2a) installed centrally.

Regards,

Tom

Dr Tom Smith
CGAT Training Fellow | http://www.cgat.org
MRC Functional Genomics Unit | University of Oxford
+44 1865 285854 | Thomas.Smith2@dpag.ox.ac.uk
________________________________

**Comment by ndaniel** [comment]
Hi Tom!

FusionCatcher prints at the terminal the exact command and its command line parameters and options which are run. One can easily copy paste these and run the command (or step) of FusionCatcher.

Therefore the tools, and in this case STAR are executed without giving their explicit paths. Thus it may very well be that FusionCatcher is executing a instance of STAR which is installed centrally.

In general, the bootstrap.py at installation phase writes the paths of the (installed) tools in fusioncatcher/etc/configuration.cfg and from here they are read and added (in front of everything else) to the environment PATH variable at execution time by FusionCatcher. Therefore the easiest way to fix the issue where FusionCatcher is using a incompatible STAR version is to specify the path to the compatible version of STAR in fusioncatcher/etc/configuration.cfg 

One may find out exactly what version of STAR (and the other tools) used by FusionCatcher in the file info.txt, which in your case would be something like:

```
grep STAR_ /ifs/projects/proj047/RNA_Seq/fusions2/test-results3/info.txt
```
Also it is highly recommended to always run the installation test script (that is fusioncatcher/test/test.sh for version 0.99.4c) immediately after FusionCatcher has been installed in order to test the installation.

**Comment by TomSmithCGAT** [comment]
Hi Daniel,

I've been running fusioncatcher on the test data as specified in the google code documentation. I get the same result if I use the test script as you describe.

If I prepend my job with following command it works fine and the info.txt file indicates that the correct version of STAR is being used (2.4.1c).

PATH=/ifs/apps/bio/fusionCatcher-0.99.4b/fusioncatcher/tools/star/bin/Linux_x86_64/:$PATH;

I'm wondering if there is an issue with fusioncatcher adding the paths from the configuration file on the front of the path at executation. Can you point me to where in the script the PATH prepending is performed?

Thanks for all your time,

Tom


Dr Tom Smith
CGAT Training Fellow | http://www.cgat.org
MRC Functional Genomics Unit | University of Oxford
+44 1865 285854 | Thomas.Smith2@dpag.ox.ac.uk
________________________________

**Comment by ndaniel** [comment]
Hi Tom!

That is line 75 in here: http://github.com/ndaniel/fusioncatcher/blob/master/bin/configuration.py

Also this does not look right!
PATH=/ifs/apps/bio/fusionCatcher-0.99.4b/fusioncatcher/tools/star/bin/Linux_x86_64/:$PATH;

It should be:
PATH=/ifs/apps/bio/fusionCatcher-0.99.4b/fusioncatcher/tools/star/bin/Linux_x86_64_static/:$PATH;

When you run
```
grep STAR_ info.tx
```
what exactly is shown?

**Comment by ndaniel** [comment]
In fusioncatcher/etc/configuration.cfg there should be
```
star = /ifs/apps/bio/fusionCatcher-0.99.4b/fusioncatcher/tools/star/bin/Linux_x86_64_static
```
instead of (my guess)
```
star = /ifs/apps/bio/fusionCatcher-0.99.4b/fusioncatcher/tools/star/source
```

**Comment by TomSmithCGAT** [comment]
Hi Daniel,

Yep, you're right, I forgot to use the static build. The lines in info.txt are:

STAR:
STAR_2.4.1c

We use Environment Modules (http://modules.sourceforge.net/) so I think the best way to proceed for me will be to create an executable for fusioncatcher that specifically loads the required versions immediately prior to running the fusioncatcher.py script. I'll use the documentation on dependencies to identify the exact versions which need to be installed and loaded at execution.


Cheers,

Tom


Dr Tom Smith
CGAT Training Fellow | http://www.cgat.org
MRC Functional Genomics Unit | University of Oxford
+44 1865 285854 | Thomas.Smith2@dpag.ox.ac.uk
________________________________

**Comment by ndaniel** [comment]
Hi Tom!

I think that FusionCatcher should work fine with Environment modules if the correct paths are given in
```
/ifs/apps/bio/fusionCatcher-0.99.4b/fusioncatcher/etc/configuration.cfg
```
Another guess of what my be going wrong is that probably in
```
/ifs/apps/bio/fusionCatcher-0.99.4b/fusioncatcher/etc/configuration.cfg
```
this is like this
```
star = /ifs/apps/bio/fusionCatcher-0.99.4b/fusioncatcher/tools/star/source
```
and that `make` **failed silently** (this is by design but still should not happen) in `/ifs/apps/bio/fusionCatcher-0.99.4b/fusioncatcher/tools/star/source` and not executable was generated and therefore FusionCatcher will end up using another STAR.

So my question is the following. Does this work?
```
/ifs/apps/bio/fusionCatcher-0.99.4b/fusioncatcher/tools/star/source/STAR --version
```

**Comment by ndaniel** [comment]
Basically,  `configuration.cfg` from
```
/ifs/apps/bio/fusionCatcher-0.99.4b/fusioncatcher/etc/configuration.cfg
```
was created exactly for this kind of situations like your case (i.e. loads the required versions immediately prior to running the all the tools of fusioncatcher.py script).

**Comment by TomSmithCGAT** [comment]
Hi Daniel,

I figured that was what the configuration.cfg file was for.

In answer to your question. It looks like STAR installed OK.

/ifs/apps/bio/fusionCatcher-0.99.4b/fusioncatcher/tools/star/source/STAR --version
STAR_2.4.1c

Regards,

Tom

Dr Tom Smith
CGAT Training Fellow | http://www.cgat.org
MRC Functional Genomics Unit | University of Oxford
+44 1865 285854 | Thomas.Smith2@dpag.ox.ac.uk
________________________________

**Comment by ndaniel** [comment]
Hi Tom!

It looks that there is a bug in FusionCatcher version 0.99.4c. FusionCatcher should only and only use STAR 2.4.1d (and not STAR 2.4.1c as it is installed by default by boostrap.py and it is specified in the documentation).

I already push a fixed bootstrap.py on sf.net but more patches I will push tomorrow.

Cheers,
Daniel

**Comment by ndaniel** [comment]
Hi Tom!

Sorry for the confusion but there was a bug in FusionCatcher v0.99.4c which installed by default STAR v2.4.1c instead of 2.4.1d (it is even stated in manual that it needs 2.4.1c but this is incorrect) and it has been fixed and the patches have been pushed upstream! Therefore a re-install will fix this. For more info please see: https://github.com/ndaniel/fusioncatcher/issues/5

**Comment by yhoogstrate** [comment]
Hi again Daniel,

I am really happy to read this news and I am proud of your results. I am also really glad that you not only use but also contribute to free scientific software (which I wish many more people should be doing). However, I don't see how this news is relevant to the technical implementation (i.e. whether or not to fork) we are discussing here.

Before this becomes an advertisement for FusionCatcher I shall only further respond to technical details. Unfortunately you needed to make a fork of seqtk rather than that your patches were incorporated or even fully reviewed. Creating a fork at itself is not a problem if it is only used for FusionCatcher with its built-in bootstrap method.

But now we are trying to move towards bioconda and here forks shall cause confusion when people start searching for `seqtk` and end-up with multiple results, named `seqtk-fork` and `seqtk`. It is just not intuitive and people don't know which one to choose, especially seqtk users that have nothing to do with fusioncathcer. Also from a maintainance perspective it is unnecessary to maintain software twice. When I think forking is really valuable is when projects end-up comepletely dead but I would not say this is the case here. That's why I am tyring to help you here and suggest to ask the seqtk author to reconsider reviewing and accepting your feature. I am even willing to spend time reviewing that code too. The solution would not only benefit you but also all other seqtk users and bioconda users. If it turns out this is not going to work out for seqtk, we can think of other options, but ending up with two nearly identical named forks of seqtk in bioconda does not seem like the best solution to me.

Youri
