### ISSUE TITLE
How to get fusion gene fasta sequence for validation

### ISSUE THREAD

**Issue by xflicsu** [ndaniel/fusioncatcher#41]
As asked in the title, how to get fusion gene sequence for validation (RT-PCR)?

**Comment by ndaniel** [comment]
Hi!

I am not really sure that I understand fully the question but I will try to answer it anyway.

FusionCatchers is a somatic fusion finder and its goal is to find fusion genes in RNA-seq data and its output is in the file called `final-list_candidates-fusion-genes.txt`. This file contains a lot of information about the found fusion genes, like for example, column called `Fusion_sequence` (which contains the inferred fusion junction and wehre the asterisk sign marks the junction point) might be useful in your case. That sequence from that column may be used to align it on the human genome (by copy an paste it and putting in your your favorite aligner, e.g. here: https://genome-euro.ucsc.edu/cgi-bin/hgBlat?hgsid=221935075_J8QqnQBKAewPx33EtNuCnshnxi3K&command=start ) and see where it maps and based on that info one can see exactly where is the fusion taking place. There are also the exact genomic coordinates for each fusion gene found. In Table 1 from the the manual of FusionCatcher is more information regarding the fusion genes (see: https://github.com/ndaniel/fusioncatcher/blob/master/doc/manual.md#62---output-data-output-data )

**Comment by xflicsu** [comment]
Thanks for response!
I want get full length of the new fusion transcript to validate the sequencing result.
The fusion junction sequence is only 100bp. Is it long enough to design primer for validation?
Any tools to output longer sequence containing the fusion junction sequence?

**Comment by ndaniel** [comment]
Hi!

The length of the fusion junction sequence depends on the read length. In our hands 100bp long is enough for 70% cases when designing PCR primers for fusion validation. The rest 30% it is quite easily to extend it manually after mapping the fusion junction on genome and this is done by the lab technician.

One can find fusion genes without having the full length fusion transcript. Finding the full length fusion transcript is very hard and very error prone because of alternative splicing in both transcripts. Anyway, FusionCatcher is trying to predict the reading frame of the fusion gene and for this it predicts the aminoacid sequence of the fusion protein (see column `Predicted_fused_proteins`) in cases where the reading frame is in-frame. Also it gives some coordinates for transcripts which are in-frame (see column `Predicted_fused_transcripts` which means Predicted effect of the candidate fusion gene using the annotation from Ensembl database. This is shown in format effect_gene_1/effect_gene_2, where the possible values for effect_gene_1 or effect_gene_2 are: intergenic, intronic, exonic(no-known-CDS), UTR, CDS(not-reliable-start-or-end), CDS(truncated), or CDS(complete). In case that the fusion junction for both genes is within their CDS (coding sequence) then only the values in-frame or out-of-frame will be shown.)

**Comment by ndaniel** [comment]
This will be enhancement will be available in the next release of FusionCatcher, that will be v0.99.7c.
Only for the fusion transcripts that are in-frame will be given the full DNA sequence.
