### ISSUE TITLE
Fusioncatcher uses both STAR and BLAT

### ISSUE THREAD

**Issue by komalsrathi** [ndaniel/fusioncatcher#46]
Hi,

Does fusioncatcher use BLAT and STAR both by default? I saw that `--skip-blat` and `--skip-star` both are set to `FALSE` by default. Is there a way to make fusioncatcher run faster than it already does? I am running it on 170 samples with an average file size of 6 GB. Each run is taking a lot of time:

```
fusioncatcher-batch.py -p 10 -d $fusioncatcher/data/current --input samples.txt --output outdir
```

Thanks,
Komal

**Comment by ndaniel** [comment]
Hi,

what version of FusionCatcher are you using? How long does it take per sample in your case?

The runtime of FusionCatcher depends more on the number of fusion genes that are in a sample than the number of reads. If there are no fusion genes, like for example in healthy samples, than FusionCatcher will be very fast even for 300 million reads.

Cheers,
Daniel

**Comment by komalsrathi** [comment]
Version: `fusioncatcher.py 0.99.7b beta`. You are right because I had reads with single ends and fusioncatcher run finished after giving me this error: 
```
ERROR: The input single-end reads are too short to be used by FusionCatcher!
```
For my other paired-end files, it is taking approximately 4.5 hours to run. The problem is I am running it on batch mode using the sample list as input but it is still running only one sample at a time.

**Comment by ndaniel** [comment]
Indeed the batch mode of FusionCatcher, that is `fusioncatcher-batch.py` runs one sample at the time. This is faster than running several samples simultaneously on the same computer/server.

Disabling/skipping simultaneously BLAT and STAR methods of FusionCatcher is not recommended because majority of fusion genes will be missed.

According to this article http://biorxiv.org/content/biorxiv/early/2017/03/24/120295.full.pdf (see Figure 4),  FusionCatcher is the third-fastet fusion finder.

**Comment by komalsrathi** [comment]
Thanks Daniel! It is actually quite convenient to use - I was just wishing for more :) Will close this now.
