### ISSUE TITLE
Version of data downloadable at SourceForce (v86) does not match latest version (v88)

### ISSUE THREAD

**Issue by hmgeiger** [ndaniel/fusioncatcher#49]
I am currently installing and setting up data for the latest version of FusionCatcher. I typically prefer to just download the prebuilt set of files from SourceForge, rather than using fusioncatcher-build. However I noticed that the version of the files at SourceForce is for Ensembl v86, whereas if you go to the Ensembl website the version they are currently up to is v88. Do you know why this might be, and if the v86 version will still work OK with the latest version of FusionCatcher?

I also wouldn't mind just running fusioncatcher-build if needed. Just want to get the proper annotation.

**Comment by ndaniel** [comment]
Indeed, your observation is correct. At the time when that FC's version was released the latest release of Ensembl database was release 86 but nowadays is 88. FC downloads always the latest release of Ensembl database because those URLs are stable in time.  For example, today May 24, 2017 the URL http://www.ensembl.org/biomart/martview/ (which is very fast) provides Ensembl release 88 but in October 2016 it was providing Ensembl release 86. If one wants to get Ensembl release 86 today then the new URL is http://oct2016.archive.ensembl.org/biomart/martview/ which is very **slow**.

That version of FC's was tested only and only with Ensembl release 86 and therefore it might be that it will not work with Ensembl release 88, because of reasons like:

- Ensembl did some minor changes to its database schema which break the FC's parsers,
- other external databases used by FC might need some manual help in order to match better than newer release of Ensembl (e.g. Ensembl removes a new gene or changes the name for a gene)
- and so on.

All these are minor things but have the potential to break in some cases the FC.
