### ISSUE TITLE
no parallel

### ISSUE THREAD

**Issue by igordot** [ndaniel/fusioncatcher#6]
I just upgraded to v0.99.4c (the one in bootstrap.py) from v0.99.4a. Running the latest version gives me the following error:
```
The workflow will be restarted from the beginning with step 1!
which: no parallel in ( [$PATH] )
....................
ERROR: The version of the data build does not match the version of this pipeline!
Please, run again the 'fusioncatcher-build.py' in order to fix this!
```
Is this the right parallel? Should it be included in tools directory?
http://www.gnu.org/software/parallel/

**Comment by ndaniel** [comment]
Hello!


> ERROR: The version of the data build does not match the version of this pipeline!
> Please, run again the 'fusioncatcher-build.py' in order to fix this!

The error message is about having an incompatible built organism data. I guess that in this case probably the organism built data is from FusionCatcher v0.99.4a while the scripts are from FusionCatcher v0.99.4c (because probably the '--download' command line option of bootstrap.py was not used?). If this is the case, then this can be fixed by downloading or generating the built organism data of FusionCatcher v0.99.4c, like shown here https://code.google.com/p/fusioncatcher/wiki/Manual#5.2_-_Organism's_build_data (or by running the script download.sh from the FusionCatcher v0.99.4c scripts)

> Is this the right parallel? http://www.gnu.org/software/parallel/

Yes. That is the right one.

> Should it be included in tools directory?

Officially, parallel is not supported yet in FusionCatcher. Therefore FusionCatcher runs fine without it.

**Comment by igordot** [comment]
Sorry. I thought the two errors were related. I reran again after rebuilding the reference data and everything seems to be working now.

**Comment by igordot** [comment]
I should add that I am seeing another warning/error now:
```
which: no parallel in ($PATH)
Starting...
No changes are done!
Done.
Converting...
Auto-detect found SANGER FASTQ format!
The end.
cat: write error: Broken pipe
sort: write failed: standard output: Broken pipe
sort: write error
Starting...
Reading ... /path/sample/reads_filtered_unique-mapped-genome_transcriptome_temp.map
```
It seems to complete successfully regardless.

**Comment by ndaniel** [comment]
Hi!

I am aware of these:
======================
cat: write error: Broken pipe
sort: write failed: standard output: Broken pipe
sort: write error
======================
but as far as I know they are harmless.

Cheers,
Daniel
