### ISSUE TITLE
overlapping genes

### ISSUE THREAD

**Issue by dinggens** [ndaniel/fusioncatcher#85]
How does FusionCatcher deal with overlapping genes, i.e. when one fusion partner consists of overlapping exons from multiple genes?
Is this reported in the output file, e.g. like comma separated ENSG IDs or sth. like this?
Many thanks in advance

**Comment by ndaniel** [comment]
Hi,

FusionCatcher is handling pretty well overlapping genes. For example, in case that there is an exon X which belongs to overlapping genes A and B and exon X is fused with other gene C. In this case FusionCatcher will list the candidate fusion genes, like GeneA--GeneC and GeneB--GeneC.

**Comment by dinggens** [comment]
Thank you!
So there is no scenario where the output columns Gene_1_id/Gene_2_id could contain comma (or other delimiters) separated entries of multiple ensembl IDs in one single cell, as such cases would be reported separately, right?

**Comment by ndaniel** [comment]
FusionCatcher does not present the fusion candidates like that because a candidate fusions like GeneA--GeneC and GeneB--GeneC would most likely have different:
- labels/tags (like for example known fusion for one but not the other one),
- predicted fusion protein sequences,
- predictied of fusion effect (for  example: in-frame/out-of-frame),
- etc. 

It should pretty easy to convert the format from:
```
GeneA GeneC position1:position2
GeneB GeneC position1:position2
GeneD GeneE position3:position4
```
into a command representation
```
GeneA,GeneB GeneC position1:position2
GeneD GeneE position3:position4
```
because the overlapping genes will have the same chromosomal coordinates for the fusion.

**Comment by dinggens** [comment]
That is great, as I do not want to have such a delimiter separated representation but a row separated one like yours.
Many thanks!
