### ISSUE TITLE
error applying find_fusion_genes_map.py 

### ISSUE THREAD

**Issue by dinggens** [ndaniel/fusioncatcher#89]
Hi,

I had a "key error" when running fusioncatcher.
It was due to the fact that an ENSG (ensembl) ID was missing in the data/genes_symbols.txt file.
I built my own reference data using 
fusioncatcher-build --skip-blat -g  homo_sapiens  --ftp-ensembl-path /pub/release-91 

When I added the ENSG-symbol map to the txt file, the error disappeared.
Can you explain this behaviour?

Many thanks in advance!

**Comment by dinggens** [comment]
Obviously it was due to the fact that the ENSG ID had no matching HGNC symbol (Clone-based (Ensembl) gene).
Anyhow, this error did not occur with the same installation of fusioncatcher 1 month ago.
Was there any change during this time which could lead to this error?

Many thanks!

**Comment by ndaniel** [comment]
If one runs today  
```
fusioncatcher-build --skip-blat -g homo_sapiens --ftp-ensembl-path /pub/release-91
```
will download actually Ensembl release 92 which is actually the latest release of Ensembl and not Ensembl 91 or 90. 
In order to get the built files for human organism for FusionCatcher for Ensembl release 90 then one needs to download them from [here](https://sourceforge.net/projects/fusioncatcher/files/data/).

**Comment by dinggens** [comment]
Ok, good to know. I thought the ensembl path parameter could be used to get
any version ensembl offers on their web page.
I reran it now with my old 91 version (simply copying the data folder) and
it worked without any error.
So thanks a lot for your help!

2018-04-20 9:30 GMT+02:00 Daniel Nicorici <notifications@github.com>:
