### ISSUE TITLE
GRCh37 ensemble indexes

### ISSUE THREAD

**Issue by ZhangNestor** [ndaniel/fusioncatcher#91]
Hello Daniel,

I want to ask if I use the GRCh37 human genome, how can I get the related "necessary files/indexes" files like "human_v90.tar.gz.a*" ?

Thansks,
Nestor

**Comment by ndaniel** [comment]
Hi Nestor,

FusionCatcher v1.0 works only with Ensembl release 90 which is based on GRCh38. If I remember right the latest Ensembl release based on GRCh37 was release 75. Also FusionCatcher versions are tightly linked to a very specific Ensembl release, because actually FusionCatcher uses several databases (RefSeq, GeneCode, UCSC,etc.), which have their own releases/versions, and integrating all of them is an semi-automatic process, which always requires some updates to scripts which parse those databases (e.g. databases change their schema). This means that in order to use GRCh37 one would have to use a very old version of FusionCatcher that is v0.99.3a that was released four years ago and it is not supported any more.

Cheers,
Daniel
